# Generated by Django 5.1.2 on 2024-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='goal',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='prefer_workout_ex',
            field=models.CharField(max_length=150),
        ),
    ]
