# Generated by Django 5.1.2 on 2024-12-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_plan',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercise_plan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user_plan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user_plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='created_by_ai',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='program_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Weekly_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, null=True)),
                ('focus', models.CharField(max_length=350, null=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sets', models.CharField(blank=True, max_length=15, null=True)),
                ('reps', models.CharField(blank=True, max_length=15, null=True)),
                ('rest', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('weekly_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.weekly_schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Exercise_Plan',
        ),
        migrations.DeleteModel(
            name='User_Plan',
        ),
    ]
