# Generated by Django 5.1.2 on 2024-12-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_preferences_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
