# Generated by Django 5.1.2 on 2024-12-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeCheckVerified',
        ),
    ]
